version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"
  initial:
    image: byrnedo/alpine-curl
    command: -X POST http://nsqd:4151/topic/create?topic=location
    depends_on:
      - nsqlookupd
      - nsqd
      - nsqadmin
  jaeger-collector:
      image: jaegertracing/all-in-one:1.12
      environment:
        COLLECTOR_ZIPKIN_HTTP_PORT: 9411
      ports:
        - 5775:5775/udp
        - 6831:6831/udp
        - 6832:6832/udp
        - 5778:5778
        - 16686:16686
        - 14268:14268
        - 9411:9411
  gateway:
    build:
      context: .
      dockerfile: gateway.Dockerfile
    depends_on:
      - nsqlookupd
      - nsqd
      - nsqadmin
      - initial
    environment:
      DRIVER_ENDPOINT: http://driver
      NSQ_ENDPOINT: nsqd:4150
      DEBUG: "true"
      JAEGER_ENDPOINT: http://jaeger-collector:14268/api/traces
    ports:
      - "8080:80"
      - "8000:8080"
  driver:
    build:
      context: .
      dockerfile: driver.Dockerfile
    depends_on:
      - nsqlookupd
      - nsqd
      - nsqadmin
      - initial
    environment:
      REPUTATION_ENDPOINT: http://reputation
      DEBUG: "true"
      JAEGER_ENDPOINT: http://jaeger-collector:14268/api/traces
    ports:
      - "8001:8080"
  reputation:
    build:
      context: .
      dockerfile: reputation.Dockerfile
    depends_on:
      - nsqlookupd
      - nsqd
      - nsqadmin
      - initial
    environment:
      DEBUG: "true"
      JAEGER_ENDPOINT: http://jaeger-collector:14268/api/traces
    ports:
      - "8002:8080"
  location:
    build:
      context: .
      dockerfile: location.Dockerfile
    depends_on:
      - nsqlookupd
      - nsqd
      - nsqadmin
      - initial
    environment:
      NSQLOOKUPD_ENDPOINT: nsqlookupd:4161
      DEBUG: "true"
      JAEGER_ENDPOINT: http://jaeger-collector:14268/api/traces
    ports:
      - "8003:8080"