apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsqlookupd
  labels:
    app: nsqlookupd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nsqlookupd
  template:
    metadata:
      labels:
        app: nsqlookupd
    spec:
      containers:
        - name: nsqlookupd
          image: nsqio/nsq
          imagePullPolicy: IfNotPresent
          command:
            - /nsqlookupd
          ports:
            - name: tcp
              containerPort: 4160
              protocol: TCP
            - name: http
              containerPort: 4161
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: nsqlookupd
  labels:
    app: nsqlookupd
spec:
  type: ClusterIP
  ports:
    - port: 4160
      targetPort: tcp
      protocol: TCP
      name: tcp
    - port: 4161
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: nsqlookupd
