apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsqd
  labels:
    app: nsqd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nsqd
  template:
    metadata:
      labels:
        app: nsqd
    spec:
      containers:
        - name: nsqd
          image: nsqio/nsq
          imagePullPolicy: IfNotPresent
          command:
            - /nsqd
            - --lookupd-tcp-address=nsqlookupd:4160
            - --broadcast-address=nsqd.default.svc.cluster.local
          ports:
            - name: tcp
              containerPort: 4150
              protocol: TCP
            - name: http
              containerPort: 4151
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: nsqd
  labels:
    app: nsqd
spec:
  type: ClusterIP
  ports:
    - port: 4150
      targetPort: tcp
      protocol: TCP
      name: tcp
    - port: 4151
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: nsqd
