apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.12
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 14268
              protocol: TCP
            - name: ui
              containerPort: 16686
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  type: ClusterIP
  ports:
    - port: 14268
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: jaeger
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-ui
  labels:
    app: jaeger
spec:
  type: NodePort
  ports:
    - port: 16686
      targetPort: ui
      protocol: TCP
      name: ui
  selector:
    app: jaeger
