apiVersion: apps/v1
kind: Deployment
metadata:
  name: location
  labels:
    app: location
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location
  template:
    metadata:
      labels:
        app: location
    spec:
      containers:
        - name: location
          image: kamsz/location
          imagePullPolicy: Always
          env:
            - name: NSQLOOKUPD_ENDPOINT
              value: nsqlookupd:4161
            - name: DEBUG
              value: "true"
            - name: JAEGER_ENDPOINT
              value: http://jaeger:14268/api/traces
